### ISSUE TITLE
Add support for xilinx 7 series

### ISSUE THREAD

**Issue by TomKeddie** [im-tomu/valentyusb#1]
I'm dabbling in litex by attempting to get valentyusb working on the arty.  At the moment I'm seeing synth issues due to lattice specific io instantiations at https://github.com/im-tomu/valentyusb/blob/master/valentyusb/usbcore/io.py#L47 and below.

I'd like to know if the preference is to

1. make this code portable and wire out the oe etc signals (my preference but changes the external api)
1. add per platform support to this code.

**Comment by xobs** [comment]
I've replaced these IO blocks with `TStriple()`, which is the generic version.  This ends up expanding to the same thing, so that the API does not need to change.

This is in 1d9387c3bc3cda71eac3dad63a935e278ed93ed1

**Comment by TomKeddie** [comment]
Thanks for the fast turnaround, much appreciated.  This builds under vivado now so I'll close this issue.
