### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by lromor** [im-tomu/valentyusb#4]
Are you interested in packaging this project?
Is the endgoal to include it in litex?
I would like to add a setup.py in order to include it as requirements.txt dependency in my project.

**Comment by xobs** [comment]
I'm not against packaging this project, I just don't particularly understand how it's supposed to work, or what one is supposed to do.  And I gather the defaults are wrong, or that it's very easy to do the wrong thing.  I've broken my system many times accidentally.

However, if a `setup.py` were to be provided as part of a PR, I would merge it.

**Comment by lromor** [comment]
Yes, I understand your point, the reason why I'm using it is to pack the dependencies for a litex fomu project. Instead of using lxbuildenv, I'm using a requirements.txt:

This is the "project template"

https://github.com/lromor/fomu-decelerator

**Comment by rjeschmi** [comment]
I also would find it useful for dev work. The rest of litex installs this way. I added a simple one manually and it works fine for my use, but it would be helpful to get it upstream.

**Comment by xobs** [comment]
> 
> 
> I also would find it useful for dev work. The rest of litex installs this way. I added a simple one manually and it works fine for my use, but it would be helpful to get it upstream.

Could you please submit a PR with your `setup.py` file?

**Comment by rjeschmi** [comment]
I see my PR was merged. I noticed the test failures, but they seemed to be upstream. Let me know if you prefer some mods. This can be closed if not.

https://github.com/im-tomu/valentyusb/pull/5

**Comment by xobs** [comment]
The test failures appear to be due to bitrot in the test framework.  I've opened an issue in that repository.

I have a local patch that updates the author fields, which I'll push shortly.  Aside from that, let me know if there's anything else you think this file needs.
